# Copyright 2019 Manna Harbour
# https://github.com/manna-harbour/miryoku

AUDIO_ENABLE = no
BACKLIGHT_ENABLE = no
BLUETOOTH_ENABLE = no
BOOTMAGIC_ENABLE = no
CONSOLE_ENABLE = no
FAUXCLICKY_ENABLE = no
HD44780_ENABLE = no
MOUSEKEY_ENABLE = yes
MIDI_ENABLE = no
NKRO_ENABLE = no
RGBLIGHT_ENABLE = yes
SLEEP_LED_ENABLE = no
UNICODE_ENABLE =no
LTO_ENABLE = yes
EXTRAFLAGS += -flto
COMMAND_ENABLE = no
SPACE_CADET_ENABLE = no
GRAVE_ESC_ENABLE = no 
MAGIC_ENABLE = no
AVR_USE_MINIMAL_PRINTF = yes
MUSIC_ENABLE = no
